markdown: rdiscount
permalink: /:title/
url: http://zionyz.github.io
name: zionyz.github.io
author: zionyz
qq: 562570576
email: zhouziy@hotmail.com
duoshuo: zionyz
beian: 浙ICP备12026616号
cnzz: 119959
github: zionyz
pygments: true
safe: true
paginate: 20
about: "这里是 zionyz 的个人博客，始建于 2016 年 github，分享个人学习心得！"
